#!/bin/bash
echo "Démarrage du flux multiplex $1"
killall dvblast
if [ $1 -eq 1 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 690000000 -c /home/alarm/Documents/rasp-dvb/dvblast.1.conf >/dev/null &
elif [ $1 -eq 2 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 770000000 -c /home/alarm/Documents/rasp-dvb/dvblast.2.conf >/dev/null &
elif [ $1 -eq 3 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 770000000 -c /home/alarm/Documents/rasp-dvb/dvblast.3.conf >/dev/null &
elif [ $1 -eq 4 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 530000000 -c /home/alarm/Documents/rasp-dvb/dvblast.4.conf >/dev/null &
elif [ $1 -eq 5 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 506000000 -c /home/alarm/Documents/rasp-dvb/dvblast.5.conf >/dev/null &
elif [ $1 -eq 6 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 506000000 -c /home/alarm/Documents/rasp-dvb/dvblast.6.conf >/dev/null &
elif [ $1 -eq 7 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 506000000 -c /home/alarm/Documents/rasp-dvb/dvblast.7.conf >/dev/null &
elif [ $1 -eq 8 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 738000000 -c /home/alarm/Documents/rasp-dvb/dvblast.8.conf >/dev/null &
elif [ $1 -eq 9 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 506000000 -c /home/alarm/Documents/rasp-dvb/dvblast.9.conf >/dev/null &
elif [ $1 -eq 10 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 690000000 -c /home/alarm/Documents/rasp-dvb/dvblast.10.conf >/dev/null &
elif [ $1 -eq 11 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 690000000 -c /home/alarm/Documents/rasp-dvb/dvblast.11.conf >/dev/null &
elif [ $1 -eq 12 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 690000000 -c /home/alarm/Documents/rasp-dvb/dvblast.12.conf >/dev/null &
elif [ $1 -eq 13 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 690000000 -c /home/alarm/Documents/rasp-dvb/dvblast.13.conf >/dev/null &
elif [ $1 -eq 14 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 770000000 -c /home/alarm/Documents/rasp-dvb/dvblast.14.conf >/dev/null &
elif [ $1 -eq 15 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 738000000 -c /home/alarm/Documents/rasp-dvb/dvblast.15.conf >/dev/null &
elif [ $1 -eq 16 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 738000000 -c /home/alarm/Documents/rasp-dvb/dvblast.16.conf >/dev/null &
elif [ $1 -eq 17 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 738000000 -c /home/alarm/Documents/rasp-dvb/dvblast.17.conf >/dev/null &
elif [ $1 -eq 18 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 738000000 -c /home/alarm/Documents/rasp-dvb/dvblast.18.conf >/dev/null &
elif [ $1 -eq 19 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 770000000 -c /home/alarm/Documents/rasp-dvb/dvblast.19.conf >/dev/null &
elif [ $1 -eq 20 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 538000000 -c /home/alarm/Documents/rasp-dvb/dvblast.20.conf >/dev/null &
elif [ $1 -eq 21 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 538000000 -c /home/alarm/Documents/rasp-dvb/dvblast.21.conf >/dev/null &
elif [ $1 -eq 22 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 506000000 -c /home/alarm/Documents/rasp-dvb/dvblast.22.conf >/dev/null &
elif [ $1 -eq 23 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 538000000 -c /home/alarm/Documents/rasp-dvb/dvblast.23.conf >/dev/null &
elif [ $1 -eq 24 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 538000000 -c /home/alarm/Documents/rasp-dvb/dvblast.24.conf >/dev/null &
elif [ $1 -eq 25 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 538000000 -c /home/alarm/Documents/rasp-dvb/dvblast.25.conf >/dev/null &
elif [ $1 -eq 26 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 530000000 -c /home/alarm/Documents/rasp-dvb/dvblast.26.conf >/dev/null &
elif [ $1 -eq 27 ]
then
    rm -f /tmp/dvblast.sock
    dvblast -e -qq -t0 -r /tmp/dvblast.sock -a 0 -f 770000000 -c /home/alarm/Documents/rasp-dvb/dvblast.27.conf >/dev/null &
else
    echo "Channel doesn't exist"
fi
